#!/bin/bash -l
module load bcftools/1.12
module load plink2/2.00a2.3
#$ -m ea
#$ -M zainabk@bu.edu

chr=$1
out1=chr${chr}_20K_36K
out2=chr${chr}_20K_36K_step4_new_indep50g0.05m0.01
out3=chr${chr}_20K_36K_step4.pruned_g0.05m0.01indep50
#pruning, select high callrate, pass hwe test, common variants, pruned
plink2 --bfile ${out1}  --geno 0.05  --maf 0.01 --indep-pairwise 50 5 0.5 --set-all-var-ids @_#  --out ${out2}

#pull out those pruned variants from plink file
plink2 --bfile  ${out1}   --extract  ${out2}.prune.in --set-all-var-ids @_# --make-bed --out ${out3}
